// AUTO-GENERATED by scripts/gen-idl.js — do not edit.
// Source: program/target/idl/roda_vault.json
export const RODA_IDL = {
  "address": "5gA8XF9AuVoYkSAjMvqk7xpDDaV4Au5HGQwcEcyM9UXJ",
  "metadata": {
    "name": "roda_vault",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Created with Anchor"
  },
  "instructions": [
    {
      "name": "claim_name",
      "discriminator": [
        198,
        183,
        177,
        101,
        183,
        218,
        69,
        237
      ],
      "accounts": [
        {
          "name": "profile",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  112,
                  114,
                  111,
                  102,
                  105,
                  108,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              }
            ]
          }
        },
        {
          "name": "name_record",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  110,
                  97,
                  109,
                  101
                ]
              },
              {
                "kind": "arg",
                "path": "name"
              }
            ]
          }
        },
        {
          "name": "old_name_record",
          "docs": [
            "Previous name account — only supplied when renaming (profile.name non-empty)."
          ],
          "writable": true,
          "optional": true
        },
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "name",
          "type": "string"
        }
      ]
    },
    {
      "name": "claim_payout",
      "discriminator": [
        127,
        240,
        132,
        62,
        227,
        198,
        146,
        133
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "circle",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "circle.id",
                "account": "Circle"
              }
            ]
          }
        },
        {
          "name": "circle_authority",
          "docs": [
            "Circle treasury authority PDA."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "circle"
              }
            ]
          }
        },
        {
          "name": "token_mint",
          "docs": [
            "The USDC token mint."
          ]
        },
        {
          "name": "fee_recipient",
          "docs": [
            "Protocol fee recipient, fixed to the configured deployer/admin."
          ]
        },
        {
          "name": "fee_token_account",
          "docs": [
            "Deployer/admin's USDC token account for the protocol fee."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "fee_recipient"
              },
              {
                "kind": "const",
                "value": [
                  6,
                  221,
                  246,
                  225,
                  215,
                  101,
                  161,
                  147,
                  217,
                  203,
                  225,
                  70,
                  206,
                  235,
                  121,
                  172,
                  28,
                  180,
                  133,
                  237,
                  95,
                  91,
                  55,
                  145,
                  58,
                  140,
                  245,
                  133,
                  126,
                  255,
                  0,
                  169
                ]
              },
              {
                "kind": "account",
                "path": "token_mint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "recipient_token_account",
          "docs": [
            "The current round's recipient (signer)."
          ],
          "writable": true
        },
        {
          "name": "circle_token_account",
          "docs": [
            "Circle treasury ATA (source)."
          ],
          "writable": true
        },
        {
          "name": "recipient",
          "writable": true,
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "associated_token_program",
          "address": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "close_circle",
      "discriminator": [
        249,
        63,
        161,
        46,
        147,
        239,
        34,
        37
      ],
      "accounts": [
        {
          "name": "circle",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "circle.id",
                "account": "Circle"
              }
            ]
          }
        },
        {
          "name": "circle_authority",
          "docs": [
            "Circle treasury authority PDA."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "circle"
              }
            ]
          }
        },
        {
          "name": "circle_token_account",
          "docs": [
            "Circle treasury ATA — must be empty."
          ],
          "writable": true
        },
        {
          "name": "creator",
          "writable": true,
          "signer": true,
          "relations": [
            "circle"
          ]
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "close_vault",
      "discriminator": [
        141,
        103,
        17,
        126,
        72,
        75,
        29,
        29
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.vault_id",
                "account": "UserVault"
              }
            ]
          }
        },
        {
          "name": "vault_authority",
          "docs": [
            "Vault authority PDA — used to close the vault's token account."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "vault"
              }
            ]
          }
        },
        {
          "name": "vault_token_account",
          "docs": [
            "Vault's ATA to close — must be the vault's own ATA and empty."
          ],
          "writable": true
        },
        {
          "name": "owner",
          "docs": [
            "Receives the rent from the closed vault token account."
          ],
          "writable": true,
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "contribute",
      "discriminator": [
        82,
        33,
        68,
        131,
        32,
        0,
        205,
        95
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "circle",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "circle.id",
                "account": "Circle"
              }
            ]
          }
        },
        {
          "name": "member_account",
          "docs": [
            "The signer's membership record for this circle."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  109,
                  101,
                  109,
                  98,
                  101,
                  114
                ]
              },
              {
                "kind": "account",
                "path": "circle"
              },
              {
                "kind": "account",
                "path": "owner"
              }
            ]
          }
        },
        {
          "name": "circle_authority",
          "docs": [
            "Circle treasury authority PDA."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "circle"
              }
            ]
          }
        },
        {
          "name": "token_mint",
          "docs": [
            "The USDC token mint."
          ]
        },
        {
          "name": "user_token_account",
          "docs": [
            "Member's token account (source of funds)."
          ],
          "writable": true
        },
        {
          "name": "circle_token_account",
          "docs": [
            "Circle treasury ATA (destination)."
          ],
          "writable": true
        },
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "create_circle",
      "discriminator": [
        186,
        99,
        49,
        131,
        31,
        51,
        13,
        198
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "circle",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101
                ]
              },
              {
                "kind": "arg",
                "path": "circle_code"
              }
            ]
          }
        },
        {
          "name": "creator_member",
          "docs": [
            "Creator's membership record (creator is always member #1)."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  109,
                  101,
                  109,
                  98,
                  101,
                  114
                ]
              },
              {
                "kind": "account",
                "path": "circle"
              },
              {
                "kind": "account",
                "path": "creator"
              }
            ]
          }
        },
        {
          "name": "circle_authority",
          "docs": [
            "Circle treasury authority PDA — signs circle token transfers."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "circle"
              }
            ]
          }
        },
        {
          "name": "token_mint",
          "docs": [
            "The USDC token mint."
          ]
        },
        {
          "name": "circle_token_account",
          "docs": [
            "Circle treasury ATA. Created if needed."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "circle_authority"
              },
              {
                "kind": "const",
                "value": [
                  6,
                  221,
                  246,
                  225,
                  215,
                  101,
                  161,
                  147,
                  217,
                  203,
                  225,
                  70,
                  206,
                  235,
                  121,
                  172,
                  28,
                  180,
                  133,
                  237,
                  95,
                  91,
                  55,
                  145,
                  58,
                  140,
                  245,
                  133,
                  126,
                  255,
                  0,
                  169
                ]
              },
              {
                "kind": "account",
                "path": "token_mint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "creator",
          "writable": true,
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "associated_token_program",
          "address": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "circle_code",
          "type": "u64"
        },
        {
          "name": "name",
          "type": "string"
        },
        {
          "name": "max_members",
          "type": "u8"
        },
        {
          "name": "contribution_amount",
          "type": "u64"
        },
        {
          "name": "frequency_secs",
          "type": "i64"
        }
      ]
    },
    {
      "name": "create_vault",
      "discriminator": [
        29,
        237,
        247,
        208,
        193,
        82,
        54,
        135
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "config.vault_count",
                "account": "RodaConfig"
              }
            ]
          }
        },
        {
          "name": "token_mint",
          "docs": [
            "The USDC token mint."
          ]
        },
        {
          "name": "vault_authority",
          "docs": [
            "Vault authority PDA — used to sign token transfers on behalf of the vault."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "vault"
              }
            ]
          }
        },
        {
          "name": "vault_token_account",
          "docs": [
            "Vault's ATA for the token mint. Created if needed."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "vault_authority"
              },
              {
                "kind": "const",
                "value": [
                  6,
                  221,
                  246,
                  225,
                  215,
                  101,
                  161,
                  147,
                  217,
                  203,
                  225,
                  70,
                  206,
                  235,
                  121,
                  172,
                  28,
                  180,
                  133,
                  237,
                  95,
                  91,
                  55,
                  145,
                  58,
                  140,
                  245,
                  133,
                  126,
                  255,
                  0,
                  169
                ]
              },
              {
                "kind": "account",
                "path": "token_mint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "associated_token_program",
          "address": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        },
        {
          "name": "rent",
          "address": "SysvarRent111111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "tier",
          "type": {
            "defined": {
              "name": "VaultTier"
            }
          }
        }
      ]
    },
    {
      "name": "deposit",
      "discriminator": [
        242,
        35,
        198,
        137,
        82,
        225,
        242,
        182
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.vault_id",
                "account": "UserVault"
              }
            ]
          }
        },
        {
          "name": "vault_authority",
          "docs": [
            "Vault authority PDA — signs token transfers."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "vault"
              }
            ]
          }
        },
        {
          "name": "token_mint",
          "docs": [
            "The USDC token mint."
          ]
        },
        {
          "name": "user_token_account",
          "docs": [
            "User's token account (source of funds)."
          ],
          "writable": true
        },
        {
          "name": "vault_token_account",
          "docs": [
            "Vault's ATA (destination) — must be the vault's own ATA."
          ],
          "writable": true
        },
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "initialize_config",
      "discriminator": [
        208,
        127,
        21,
        1,
        194,
        190,
        196,
        70
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "usdc_mint",
          "docs": [
            "The USDC mint all vaults and circles will use."
          ]
        },
        {
          "name": "admin",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "join_circle",
      "discriminator": [
        231,
        168,
        235,
        18,
        99,
        12,
        22,
        7
      ],
      "accounts": [
        {
          "name": "circle",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  105,
                  114,
                  99,
                  108,
                  101
                ]
              },
              {
                "kind": "arg",
                "path": "circle_id"
              }
            ]
          }
        },
        {
          "name": "member_account",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  109,
                  101,
                  109,
                  98,
                  101,
                  114
                ]
              },
              {
                "kind": "account",
                "path": "circle"
              },
              {
                "kind": "account",
                "path": "member"
              }
            ]
          }
        },
        {
          "name": "member",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": [
        {
          "name": "circle_id",
          "type": "u64"
        }
      ]
    },
    {
      "name": "release_name",
      "discriminator": [
        3,
        68,
        17,
        217,
        57,
        53,
        123,
        164
      ],
      "accounts": [
        {
          "name": "profile",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  112,
                  114,
                  111,
                  102,
                  105,
                  108,
                  101
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              }
            ]
          }
        },
        {
          "name": "name_record",
          "docs": [
            "The RegisteredName PDA for the profile's current name."
          ],
          "writable": true
        },
        {
          "name": "owner",
          "writable": true,
          "signer": true
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "request_usdc",
      "discriminator": [
        61,
        17,
        172,
        32,
        146,
        52,
        83,
        35
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "mint",
          "docs": [
            "The Roda USDC mint (must be the configured mint)."
          ],
          "writable": true
        },
        {
          "name": "faucet_authority",
          "docs": [
            "Faucet authority PDA — the mint's mint_authority."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  102,
                  97,
                  117,
                  99,
                  101,
                  116
                ]
              }
            ]
          }
        },
        {
          "name": "faucet_info",
          "docs": [
            "Per-user cooldown record."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  102,
                  97,
                  117,
                  99,
                  101,
                  116,
                  95,
                  105,
                  110,
                  102,
                  111
                ]
              },
              {
                "kind": "account",
                "path": "user"
              }
            ]
          }
        },
        {
          "name": "user_token_account",
          "docs": [
            "User's USDC ATA. Created if needed."
          ],
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "account",
                "path": "user"
              },
              {
                "kind": "const",
                "value": [
                  6,
                  221,
                  246,
                  225,
                  215,
                  101,
                  161,
                  147,
                  217,
                  203,
                  225,
                  70,
                  206,
                  235,
                  121,
                  172,
                  28,
                  180,
                  133,
                  237,
                  95,
                  91,
                  55,
                  145,
                  58,
                  140,
                  245,
                  133,
                  126,
                  255,
                  0,
                  169
                ]
              },
              {
                "kind": "account",
                "path": "mint"
              }
            ],
            "program": {
              "kind": "const",
              "value": [
                140,
                151,
                37,
                143,
                78,
                36,
                137,
                241,
                187,
                61,
                16,
                41,
                20,
                142,
                13,
                131,
                11,
                90,
                19,
                153,
                218,
                255,
                16,
                132,
                4,
                142,
                123,
                216,
                219,
                233,
                248,
                89
              ]
            }
          }
        },
        {
          "name": "user",
          "writable": true,
          "signer": true
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        },
        {
          "name": "associated_token_program",
          "address": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
        },
        {
          "name": "system_program",
          "address": "11111111111111111111111111111111"
        }
      ],
      "args": []
    },
    {
      "name": "set_usdc_mint",
      "discriminator": [
        134,
        188,
        41,
        199,
        126,
        105,
        241,
        157
      ],
      "accounts": [
        {
          "name": "config",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "usdc_mint",
          "docs": [
            "The new USDC mint (6 decimals)."
          ]
        },
        {
          "name": "admin",
          "docs": [
            "Config admin — the wallet that ran initialize_config."
          ],
          "signer": true
        }
      ],
      "args": []
    },
    {
      "name": "withdraw",
      "discriminator": [
        183,
        18,
        70,
        156,
        148,
        109,
        161,
        34
      ],
      "accounts": [
        {
          "name": "config",
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  99,
                  111,
                  110,
                  102,
                  105,
                  103
                ]
              }
            ]
          }
        },
        {
          "name": "vault",
          "writable": true,
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116
                ]
              },
              {
                "kind": "account",
                "path": "owner"
              },
              {
                "kind": "account",
                "path": "vault.vault_id",
                "account": "UserVault"
              }
            ]
          }
        },
        {
          "name": "vault_authority",
          "docs": [
            "Vault authority PDA — signs the withdrawal transfer."
          ],
          "pda": {
            "seeds": [
              {
                "kind": "const",
                "value": [
                  114,
                  111,
                  100,
                  97,
                  95,
                  118,
                  97,
                  117,
                  108,
                  116,
                  95,
                  97,
                  117,
                  116,
                  104
                ]
              },
              {
                "kind": "account",
                "path": "vault"
              }
            ]
          }
        },
        {
          "name": "token_mint",
          "docs": [
            "The USDC token mint."
          ]
        },
        {
          "name": "user_token_account",
          "docs": [
            "User's token account (destination)."
          ],
          "writable": true
        },
        {
          "name": "vault_token_account",
          "docs": [
            "Vault's ATA (source) — must be the vault's own ATA."
          ],
          "writable": true
        },
        {
          "name": "owner",
          "writable": true,
          "signer": true,
          "relations": [
            "vault"
          ]
        },
        {
          "name": "token_program",
          "address": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "Circle",
      "discriminator": [
        27,
        59,
        8,
        117,
        62,
        199,
        222,
        252
      ]
    },
    {
      "name": "CircleMember",
      "discriminator": [
        85,
        223,
        111,
        90,
        181,
        242,
        179,
        231
      ]
    },
    {
      "name": "FaucetInfo",
      "discriminator": [
        74,
        95,
        172,
        216,
        186,
        30,
        36,
        179
      ]
    },
    {
      "name": "NameProfile",
      "discriminator": [
        3,
        247,
        89,
        150,
        42,
        45,
        170,
        128
      ]
    },
    {
      "name": "RegisteredName",
      "discriminator": [
        134,
        103,
        50,
        107,
        5,
        33,
        23,
        71
      ]
    },
    {
      "name": "RodaConfig",
      "discriminator": [
        74,
        138,
        52,
        10,
        102,
        188,
        88,
        131
      ]
    },
    {
      "name": "UserVault",
      "discriminator": [
        23,
        76,
        96,
        159,
        210,
        10,
        5,
        22
      ]
    }
  ],
  "events": [
    {
      "name": "CircleClosed",
      "discriminator": [
        205,
        90,
        185,
        247,
        113,
        234,
        159,
        176
      ]
    },
    {
      "name": "CircleCreated",
      "discriminator": [
        210,
        110,
        215,
        179,
        247,
        145,
        243,
        135
      ]
    },
    {
      "name": "ContributionMade",
      "discriminator": [
        81,
        218,
        72,
        109,
        93,
        96,
        131,
        199
      ]
    },
    {
      "name": "FaucetClaimed",
      "discriminator": [
        153,
        213,
        25,
        224,
        176,
        249,
        203,
        218
      ]
    },
    {
      "name": "MemberJoined",
      "discriminator": [
        156,
        199,
        149,
        88,
        193,
        203,
        191,
        210
      ]
    },
    {
      "name": "NameClaimed",
      "discriminator": [
        144,
        186,
        138,
        164,
        35,
        56,
        124,
        160
      ]
    },
    {
      "name": "NameReleased",
      "discriminator": [
        40,
        189,
        0,
        197,
        89,
        167,
        209,
        69
      ]
    },
    {
      "name": "PayoutReleased",
      "discriminator": [
        245,
        195,
        37,
        2,
        200,
        70,
        126,
        210
      ]
    },
    {
      "name": "VaultClosed",
      "discriminator": [
        238,
        129,
        38,
        228,
        227,
        118,
        249,
        215
      ]
    },
    {
      "name": "VaultCreated",
      "discriminator": [
        117,
        25,
        120,
        254,
        75,
        236,
        78,
        115
      ]
    },
    {
      "name": "VaultDeposit",
      "discriminator": [
        4,
        248,
        234,
        163,
        99,
        238,
        140,
        45
      ]
    },
    {
      "name": "VaultWithdraw",
      "discriminator": [
        133,
        90,
        194,
        198,
        170,
        52,
        90,
        180
      ]
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "BelowMinimum",
      "msg": "Deposit amount is below the tier minimum."
    },
    {
      "code": 6001,
      "name": "VaultNotMatured",
      "msg": "Vault has not matured yet."
    },
    {
      "code": 6002,
      "name": "VaultNotActive",
      "msg": "Vault is not active."
    },
    {
      "code": 6003,
      "name": "VaultAlreadyClosed",
      "msg": "Vault is already closed."
    },
    {
      "code": 6004,
      "name": "InsufficientBalance",
      "msg": "Insufficient vault balance."
    },
    {
      "code": 6005,
      "name": "Unauthorized",
      "msg": "Unauthorized — only vault owner can perform this action."
    },
    {
      "code": 6006,
      "name": "SameBlockWithdraw",
      "msg": "Cannot withdraw in the same block as deposit."
    },
    {
      "code": 6007,
      "name": "TransferFailed",
      "msg": "Token transfer failed."
    },
    {
      "code": 6008,
      "name": "MathOverflow",
      "msg": "Math overflow."
    },
    {
      "code": 6009,
      "name": "InvalidMint",
      "msg": "Wrong token mint — expected the Roda USDC mint."
    },
    {
      "code": 6010,
      "name": "InvalidAmount",
      "msg": "Amount must be greater than zero."
    },
    {
      "code": 6011,
      "name": "InvalidCircleName",
      "msg": "Circle name must be 3-32 characters."
    },
    {
      "code": 6012,
      "name": "InvalidMemberCount",
      "msg": "max_members must be between 2 and 12."
    },
    {
      "code": 6013,
      "name": "InvalidContribution",
      "msg": "Contribution amount must be greater than zero."
    },
    {
      "code": 6014,
      "name": "InvalidFrequency",
      "msg": "Round frequency must be at least 60 seconds."
    },
    {
      "code": 6015,
      "name": "CircleFull",
      "msg": "Circle is full."
    },
    {
      "code": 6016,
      "name": "CircleNotFull",
      "msg": "Circle is not full yet."
    },
    {
      "code": 6017,
      "name": "CircleNotJoinable",
      "msg": "Circle is not open for new members right now."
    },
    {
      "code": 6018,
      "name": "AlreadyPaid",
      "msg": "You already paid for the current round."
    },
    {
      "code": 6019,
      "name": "NotAllPaid",
      "msg": "Not all members have paid for the current round yet."
    },
    {
      "code": 6020,
      "name": "RoundNotReady",
      "msg": "The current round payout is not available yet."
    },
    {
      "code": 6021,
      "name": "NotYourPayout",
      "msg": "It is not your turn to receive the payout."
    },
    {
      "code": 6022,
      "name": "CircleNotCompleted",
      "msg": "Circle has not completed all rounds yet."
    },
    {
      "code": 6023,
      "name": "NameTaken",
      "msg": "Username is already taken."
    },
    {
      "code": 6024,
      "name": "NameNotSet",
      "msg": "This wallet has no username set."
    },
    {
      "code": 6025,
      "name": "NameTooShort",
      "msg": "Username must be at least 3 characters."
    },
    {
      "code": 6026,
      "name": "NameTooLong",
      "msg": "Username must be at most 20 characters."
    },
    {
      "code": 6027,
      "name": "InvalidNameChars",
      "msg": "Username may only contain lowercase letters, numbers and underscores."
    },
    {
      "code": 6028,
      "name": "CooldownActive",
      "msg": "24-hour cooldown active — try again later."
    },
    {
      "code": 6029,
      "name": "OldNameRecordRequired",
      "msg": "Previous name account must be provided to change usernames."
    },
    {
      "code": 6030,
      "name": "FaucetCooldown",
      "msg": "Faucet cooldown active — claim again tomorrow."
    },
    {
      "code": 6031,
      "name": "FaucetUnavailable",
      "msg": "Faucet unavailable — it can only mint the Roda test USDC, not the configured mint."
    },
    {
      "code": 6032,
      "name": "InvalidCircleCode",
      "msg": "Circle code must be a 6-digit number (100000-999999)."
    }
  ],
  "types": [
    {
      "name": "Circle",
      "docs": [
        "Rotating savings (ajo/esusu) circle."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "id",
            "docs": [
              "Stable numeric ID (join-by-id, display)."
            ],
            "type": "u64"
          },
          {
            "name": "creator",
            "docs": [
              "Wallet that created the circle."
            ],
            "type": "pubkey"
          },
          {
            "name": "name",
            "docs": [
              "Display name (3-32 chars, reserved capacity)."
            ],
            "type": "string"
          },
          {
            "name": "max_members",
            "docs": [
              "Maximum members allowed."
            ],
            "type": "u8"
          },
          {
            "name": "member_count",
            "docs": [
              "Current number of joined members."
            ],
            "type": "u8"
          },
          {
            "name": "paid_count",
            "docs": [
              "Members who paid for the current round."
            ],
            "type": "u8"
          },
          {
            "name": "contribution_amount",
            "docs": [
              "Fixed contribution per member per round (USDC, 6 decimals)."
            ],
            "type": "u64"
          },
          {
            "name": "frequency_secs",
            "docs": [
              "Seconds between rounds (informational schedule)."
            ],
            "type": "i64"
          },
          {
            "name": "current_round",
            "docs": [
              "Round currently collecting contributions (0-based)."
            ],
            "type": "u16"
          },
          {
            "name": "pool_balance",
            "docs": [
              "USDC held in the circle treasury for the current round."
            ],
            "type": "u64"
          },
          {
            "name": "round_started_ts",
            "docs": [
              "Unix timestamp when the current round started."
            ],
            "type": "i64"
          },
          {
            "name": "status",
            "docs": [
              "Active until all rounds complete."
            ],
            "type": {
              "defined": {
                "name": "CircleStatus"
              }
            }
          },
          {
            "name": "members",
            "docs": [
              "Member wallets in join order; payout for round R goes to members[R % member_count]."
            ],
            "type": {
              "vec": "pubkey"
            }
          },
          {
            "name": "bump",
            "docs": [
              "PDA bump seed."
            ],
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "CircleClosed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "circle_id",
            "type": "u64"
          },
          {
            "name": "by",
            "type": "pubkey"
          }
        ]
      }
    },
    {
      "name": "CircleCreated",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "circle_id",
            "type": "u64"
          },
          {
            "name": "creator",
            "type": "pubkey"
          },
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "max_members",
            "type": "u8"
          },
          {
            "name": "contribution_amount",
            "type": "u64"
          },
          {
            "name": "frequency_secs",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "CircleMember",
      "docs": [
        "Per-member position inside a circle."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "circle",
            "docs": [
              "Circle this membership belongs to."
            ],
            "type": "pubkey"
          },
          {
            "name": "member",
            "docs": [
              "Member wallet."
            ],
            "type": "pubkey"
          },
          {
            "name": "joined_round",
            "docs": [
              "Round in which the member joined."
            ],
            "type": "u16"
          },
          {
            "name": "paid_round",
            "docs": [
              "Round the member last paid for (PAID_ROUND_NONE = never)."
            ],
            "type": "u16"
          },
          {
            "name": "bump",
            "docs": [
              "PDA bump seed."
            ],
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "CircleStatus",
      "docs": [
        "Lifecycle state of a rotating savings circle."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Active"
          },
          {
            "name": "Completed"
          }
        ]
      }
    },
    {
      "name": "ContributionMade",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "circle_id",
            "type": "u64"
          },
          {
            "name": "member",
            "type": "pubkey"
          },
          {
            "name": "round",
            "type": "u16"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "paid_count",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "FaucetClaimed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "amount",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "FaucetInfo",
      "docs": [
        "Per-user faucet cooldown record."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "user",
            "docs": [
              "Wallet that claimed."
            ],
            "type": "pubkey"
          },
          {
            "name": "last_claim_ts",
            "docs": [
              "Unix timestamp of the last claim (0 = never)."
            ],
            "type": "i64"
          },
          {
            "name": "bump",
            "docs": [
              "PDA bump seed."
            ],
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "MemberJoined",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "circle_id",
            "type": "u64"
          },
          {
            "name": "member",
            "type": "pubkey"
          },
          {
            "name": "member_count",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "NameClaimed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "name",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "NameProfile",
      "docs": [
        "Per-owner username profile (reverse lookup + cooldown bookkeeping)."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "docs": [
              "Wallet that owns the username."
            ],
            "type": "pubkey"
          },
          {
            "name": "name",
            "docs": [
              "Current lowercase username (\"\" when released)."
            ],
            "type": "string"
          },
          {
            "name": "last_change_ts",
            "docs": [
              "Unix timestamp of the last claim/release (cooldown gate)."
            ],
            "type": "i64"
          },
          {
            "name": "bump",
            "docs": [
              "PDA bump seed."
            ],
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "NameReleased",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "name",
            "type": "string"
          }
        ]
      }
    },
    {
      "name": "PayoutReleased",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "circle_id",
            "type": "u64"
          },
          {
            "name": "recipient",
            "type": "pubkey"
          },
          {
            "name": "round",
            "type": "u16"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "next_round",
            "type": "u16"
          },
          {
            "name": "completed",
            "type": "bool"
          }
        ]
      }
    },
    {
      "name": "RegisteredName",
      "docs": [
        "Onchain username registration (name → owner)."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "docs": [
              "Wallet that owns this name."
            ],
            "type": "pubkey"
          },
          {
            "name": "name",
            "docs": [
              "The registered lowercase username."
            ],
            "type": "string"
          },
          {
            "name": "claimed_at",
            "docs": [
              "Unix timestamp when claimed."
            ],
            "type": "i64"
          },
          {
            "name": "bump",
            "docs": [
              "PDA bump seed."
            ],
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "RodaConfig",
      "docs": [
        "Global Roda configuration — singleton PDA."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "docs": [
              "Admin who initialized the config."
            ],
            "type": "pubkey"
          },
          {
            "name": "usdc_mint",
            "docs": [
              "USDC token mint (SPL)."
            ],
            "type": "pubkey"
          },
          {
            "name": "vault_count",
            "docs": [
              "Auto-incrementing vault ID counter."
            ],
            "type": "u64"
          },
          {
            "name": "circle_count",
            "docs": [
              "Number of circles created so far (circle ids are client-generated 6-digit codes)."
            ],
            "type": "u64"
          },
          {
            "name": "bump",
            "docs": [
              "PDA bump seed."
            ],
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "UserVault",
      "docs": [
        "Individual user savings vault."
      ],
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "docs": [
              "The owner of this vault."
            ],
            "type": "pubkey"
          },
          {
            "name": "vault_id",
            "docs": [
              "Unique vault ID (from RodaConfig.vault_count)."
            ],
            "type": "u64"
          },
          {
            "name": "tier",
            "docs": [
              "Vault tier."
            ],
            "type": {
              "defined": {
                "name": "VaultTier"
              }
            }
          },
          {
            "name": "token_mint",
            "docs": [
              "Token mint held in this vault (USDC)."
            ],
            "type": "pubkey"
          },
          {
            "name": "balance",
            "docs": [
              "Total deposited amount (in token decimals)."
            ],
            "type": "u64"
          },
          {
            "name": "last_deposit_ts",
            "docs": [
              "Timestamp of the last deposit (governs maturity)."
            ],
            "type": "i64"
          },
          {
            "name": "maturity_ts",
            "docs": [
              "Timestamp when the vault matures (last_deposit_ts + lock_duration)."
            ],
            "type": "i64"
          },
          {
            "name": "active",
            "docs": [
              "Whether the vault is active (can receive deposits)."
            ],
            "type": "bool"
          },
          {
            "name": "bump",
            "docs": [
              "PDA bump seed."
            ],
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "VaultClosed",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "vault_id",
            "type": "u64"
          }
        ]
      }
    },
    {
      "name": "VaultCreated",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "vault_id",
            "type": "u64"
          },
          {
            "name": "tier",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "VaultDeposit",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "vault_id",
            "type": "u64"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "balance",
            "type": "u64"
          },
          {
            "name": "maturity_ts",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "VaultTier",
      "docs": [
        "Savings vault tier."
      ],
      "type": {
        "kind": "enum",
        "variants": [
          {
            "name": "Flex"
          },
          {
            "name": "Weekly"
          },
          {
            "name": "Monthly"
          },
          {
            "name": "SixMonths"
          },
          {
            "name": "OneYear"
          }
        ]
      }
    },
    {
      "name": "VaultWithdraw",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "owner",
            "type": "pubkey"
          },
          {
            "name": "vault_id",
            "type": "u64"
          },
          {
            "name": "amount",
            "type": "u64"
          },
          {
            "name": "balance",
            "type": "u64"
          }
        ]
      }
    }
  ]
} as const;
