/** Regenerates constants/idl.ts from the Anchor IDL. Run after `anchor build`. */
const fs = require('fs');
const path = require('path');
const idlPath = path.join(__dirname, '../../program/target/idl/roda_vault.json');
const idl = JSON.parse(fs.readFileSync(idlPath, 'utf8'));
const out = `// AUTO-GENERATED by scripts/gen-idl.js — do not edit.
// Source: program/target/idl/roda_vault.json
export const RODA_IDL = ${JSON.stringify(idl, null, 2)} as const;
`;
fs.writeFileSync(path.join(__dirname, '../constants/idl.ts'), out);
console.log(`constants/idl.ts written (${idl.instructions.length} instructions, ${idl.accounts.length} accounts, ${idl.events.length} events)`);
